/**
 * ViPER4Web TypeScript Types
 *
 * ViperController and MainModule types are auto-generated by Emscripten
 * from the C++ Embind bindings. See viper4web.d.ts for the generated types.
 */

// Re-export types from the Emscripten-generated declaration file
export type { ViperController, MainModule } from './viper4web';

// Import for local use
import type { MainModule } from './viper4web';

/**
 * ViperModule is an alias for MainModule with additional heap access properties
 * that are available at runtime but not in the generated declarations.
 */
export interface ViperModule extends MainModule {
  HEAPF32: Float32Array;
  HEAP8: Int8Array;
  HEAPU8: Uint8Array;
}

/**
 * Audio Queue Item - represents a single track in the queue
 */
export interface AudioQueueItem {
  id: string;
  file: File;
  name: string;
  duration: number;
  buffer: AudioBuffer | null;
}

/**
 * Repeat Mode for audio playback
 * - 'off': No repeat, stop after queue ends
 * - 'one': Repeat current track
 * - 'all': Repeat entire queue
 */
export type RepeatMode = 'off' | 'one' | 'all';

export interface ViperEffectState {
  // Master
  enabled: boolean;

  // Convolver
  convolverEnabled: boolean;
  convolverCrossChannel: number;

  // VHE
  vheEnabled: boolean;
  vheLevel: number;

  // DDC
  ddcEnabled: boolean;

  // Spectrum Extension
  spectrumExtendEnabled: boolean;
  spectrumExtendBark: number;
  spectrumExtendBarkReconstruct: number;

  // FIR Equalizer
  firEqualizerEnabled: boolean;
  firEqualizerBands: number[];

  // Field Surround
  fieldSurroundEnabled: boolean;
  fieldSurroundWidening: number;
  fieldSurroundMidImage: number;
  fieldSurroundDepth: number;

  // Differential Surround
  diffSurroundEnabled: boolean;
  diffSurroundDelay: number;

  // Reverb
  reverbEnabled: boolean;
  reverbRoomSize: number;
  reverbRoomWidth: number;
  reverbDampening: number;
  reverbWetSignal: number;
  reverbDrySignal: number;

  // AGC
  agcEnabled: boolean;
  agcRatio: number;
  agcVolume: number;
  agcMaxScaler: number;

  // Dynamic System
  dynamicSystemEnabled: boolean;
  dynamicSystemXLowFreq: number;
  dynamicSystemXHighFreq: number;
  dynamicSystemYLowFreq: number;
  dynamicSystemYHighFreq: number;
  dynamicSystemSideGainX: number;
  dynamicSystemSideGainY: number;
  dynamicSystemBassGain: number;

  // ViPER Bass
  viperBassEnabled: boolean;
  viperBassMode: number;
  viperBassFrequency: number;
  viperBassGain: number;

  // ViPER Clarity
  viperClarityEnabled: boolean;
  viperClarityMode: number;
  viperClarityGain: number;

  // Cure
  cureEnabled: boolean;
  cureLevel: number;

  // Tube Simulator
  tubeSimulatorEnabled: boolean;

  // AnalogX
  analogXEnabled: boolean;
  analogXMode: number;

  // Output
  outputVolume: number;
  outputPan: number;
  limiterThreshold: number;

  // Speaker Optimization
  speakerOptimizationEnabled: boolean;

  // FET Compressor
  fetCompressorEnabled: boolean;
  fetCompressorThreshold: number;
  fetCompressorRatio: number;
  fetCompressorKnee: number;
  fetCompressorAutoKnee: boolean;
  fetCompressorGain: number;
  fetCompressorAutoGain: boolean;
  fetCompressorAttack: number;
  fetCompressorAutoAttack: boolean;
  fetCompressorRelease: number;
  fetCompressorAutoRelease: boolean;
  fetCompressorNoClip: boolean;
}

// localStorage key for persisting effect state
export const VIPER_STORAGE_KEY = 'viper4web-effect-state';

// Check if localStorage is available (not during SSR)
function isLocalStorageAvailable(): boolean {
  try {
    return typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';
  } catch {
    return false;
  }
}

// Save effect state to localStorage
export function saveEffectState(state: ViperEffectState): void {
  if (!isLocalStorageAvailable()) return;
  try {
    localStorage.setItem(VIPER_STORAGE_KEY, JSON.stringify(state));
  } catch (err) {
    console.warn('[ViPER] Failed to save effect state to localStorage:', err);
  }
}

// Load effect state from localStorage
export function loadEffectState(): ViperEffectState | null {
  if (!isLocalStorageAvailable()) return null;
  try {
    const saved = localStorage.getItem(VIPER_STORAGE_KEY);
    if (saved) {
      const parsed = JSON.parse(saved);
      // Validate that it has the expected structure by checking a few key properties
      if (typeof parsed === 'object' && parsed !== null && 'enabled' in parsed) {
        return parsed as ViperEffectState;
      }
    }
  } catch (err) {
    console.warn('[ViPER] Failed to load effect state from localStorage:', err);
  }
  return null;
}

// Get initial effect state (from localStorage or defaults)
export function getInitialEffectState(): ViperEffectState {
  const saved = loadEffectState();
  if (saved) {
    // Merge with defaults to ensure all fields exist (in case new fields were added)
    return { ...defaultEffectState, ...saved };
  }
  return defaultEffectState;
}

export const defaultEffectState: ViperEffectState = {
  enabled: true,

  convolverEnabled: false,
  convolverCrossChannel: 0,

  vheEnabled: false,
  vheLevel: 2, // Medium level (0-4)

  ddcEnabled: false,

  spectrumExtendEnabled: false,
  spectrumExtendBark: 10,
  spectrumExtendBarkReconstruct: 10,

  firEqualizerEnabled: false,
  firEqualizerBands: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],

  fieldSurroundEnabled: false,
  fieldSurroundWidening: 50,
  fieldSurroundMidImage: 50,
  fieldSurroundDepth: 50,

  diffSurroundEnabled: false,
  diffSurroundDelay: 20,

  reverbEnabled: false,
  reverbRoomSize: 50,
  reverbRoomWidth: 70,
  reverbDampening: 50,
  reverbWetSignal: 30, // Was 0 - need some wet signal to hear reverb
  reverbDrySignal: 70,

  agcEnabled: false,
  agcRatio: 50,
  agcVolume: 100,
  agcMaxScaler: 400,

  dynamicSystemEnabled: false,
  dynamicSystemXLowFreq: 20,     // Low pass filter X - low frequency (Hz)
  dynamicSystemXHighFreq: 80,    // Low pass filter X - high frequency (Hz)
  dynamicSystemYLowFreq: 80,     // Low pass filter Y - low frequency (Hz)
  dynamicSystemYHighFreq: 300,   // Low pass filter Y - high frequency (Hz)
  dynamicSystemSideGainX: 50,    // Side gain for X channel (0-100)
  dynamicSystemSideGainY: 50,    // Side gain for Y channel (0-100)
  dynamicSystemBassGain: 50,     // Dynamic bass gain (0-100)

  viperBassEnabled: false,
  viperBassMode: 0,
  viperBassFrequency: 40,
  viperBassGain: 50, // Was 0 - need gain to hear bass boost

  viperClarityEnabled: false,
  viperClarityMode: 0,
  viperClarityGain: 50, // Was 0 - need gain to hear clarity effect

  cureEnabled: false,
  cureLevel: 1, // Medium crossfeed

  tubeSimulatorEnabled: false,

  analogXEnabled: false,
  analogXMode: 0,

  outputVolume: 100,
  outputPan: 0,
  limiterThreshold: 100,

  speakerOptimizationEnabled: false,

  fetCompressorEnabled: false,
  fetCompressorThreshold: 0,
  fetCompressorRatio: 4,
  fetCompressorKnee: 0,
  fetCompressorAutoKnee: false,
  fetCompressorGain: 0,
  fetCompressorAutoGain: true,
  fetCompressorAttack: 10,
  fetCompressorAutoAttack: false,
  fetCompressorRelease: 100,
  fetCompressorAutoRelease: false,
  fetCompressorNoClip: true,
};
